/**
 * The POSIX shell script Claude Code runs for every hook event. Kept tiny and
 * fail-open: whatever goes wrong, the agent must never block on us.
 *
 * Order of operations matters:
 *  1. `printf '{}'` first — a PermissionRequest hook with empty stdout is a
 *     "no decision", but an empty stdout on some hook kinds is read as a
 *     failure, so answer before doing anything that could fail.
 *  2. Read stdin before any early exit — bailing out with the payload unread
 *     makes Claude's writer hit EPIPE.
 *  3. Re-source the endpoint file on every run — the loopback port is random
 *     per app launch, so an agent started under a previous app process would
 *     otherwise post to a dead port for the rest of its life.
 */

export const HOOK_ENV_ENDPOINT = 'PARALLEL_CODE_HOOK_ENDPOINT';
export const HOOK_ENV_AGENT_ID = 'PARALLEL_CODE_AGENT_ID';
export const HOOK_ENV_LAUNCH_ID = 'PARALLEL_CODE_LAUNCH_ID';
export const HOOK_ENV_TASK_ID = 'PARALLEL_CODE_TASK_ID';
export const HOOK_ENV_PORT = 'PARALLEL_CODE_HOOK_PORT';
export const HOOK_ENV_TOKEN = 'PARALLEL_CODE_HOOK_TOKEN';

export const HOOK_TOKEN_HEADER = 'x-parallel-code-hook-token';
export const HOOK_AGENT_ID_HEADER = 'x-parallel-code-agent-id';
export const HOOK_LAUNCH_ID_HEADER = 'x-parallel-code-launch-id';
export const HOOK_TASK_ID_HEADER = 'x-parallel-code-task-id';

/** Env vars the PTY layer injects; env files must never be allowed to set them. */
export const HOOK_PTY_ENV_KEYS = [
  HOOK_ENV_ENDPOINT,
  HOOK_ENV_AGENT_ID,
  HOOK_ENV_TASK_ID,
  HOOK_ENV_LAUNCH_ID,
] as const;

export function buildHookScript(): string {
  return `#!/bin/sh
# Generated by Parallel Code — forwards Claude Code hook events to the app.
# Safe to delete; the app rewrites it on next launch.
printf '{}\\n'
payload=$({ command -p cat 2>/dev/null || cat; })
[ -n "$payload" ] || exit 0
# Background job workers inherit the dispatching agent's env, so the id would
# name an agent this session is not running in.
[ -z "\${CLAUDE_JOB_DIR-}" ] || exit 0
[ -n "\${${HOOK_ENV_ENDPOINT}-}" ] || exit 0
[ -n "\${${HOOK_ENV_AGENT_ID}-}" ] || exit 0
[ -n "\${${HOOK_ENV_LAUNCH_ID}-}" ] || exit 0
[ -r "$${HOOK_ENV_ENDPOINT}" ] || exit 0
. "$${HOOK_ENV_ENDPOINT}" 2>/dev/null || exit 0
[ -n "\${${HOOK_ENV_PORT}-}" ] || exit 0
[ -n "\${${HOOK_ENV_TOKEN}-}" ] || exit 0
printf '%s' "$payload" | curl -sS -X POST "http://127.0.0.1:$${HOOK_ENV_PORT}/hook/claude" \\
  --connect-timeout 0.5 --max-time 1.5 --noproxy 127.0.0.1 \\
  -H "Content-Type: application/json" \\
  -H "${HOOK_TOKEN_HEADER}: $${HOOK_ENV_TOKEN}" \\
  -H "${HOOK_AGENT_ID_HEADER}: $${HOOK_ENV_AGENT_ID}" \\
  -H "${HOOK_LAUNCH_ID_HEADER}: $${HOOK_ENV_LAUNCH_ID}" \\
  -H "${HOOK_TASK_ID_HEADER}: \${${HOOK_ENV_TASK_ID}-}" \\
  --data-binary @- >/dev/null 2>&1 || :
exit 0
`;
}

/** Contents of the endpoint file the script sources on every event. */
export function buildEndpointFile(port: number, token: string): string {
  return `${HOOK_ENV_PORT}=${port}\n${HOOK_ENV_TOKEN}=${token}\n`;
}

/**
 * Windows counterpart to {@link buildHookScript}. There is no `/bin/sh` on
 * stock Windows, so hooks run through PowerShell 5.1+ (present since Windows
 * 10) instead. Same contract: answer `{}` first, drain stdin, re-read the
 * endpoint file on every run, POST the payload, and never fail the hook.
 */
export function buildHookScriptPs1(): string {
  return `# Generated by Parallel Code — forwards Claude Code hook events to the app.
# Safe to delete; the app rewrites it on next launch.
Write-Output '{}'
# Windows PowerShell 5.1 draws a progress bar for Invoke-WebRequest, which makes it far slower.
$ProgressPreference = 'SilentlyContinue'
$payload = ($input | Out-String)
if ([string]::IsNullOrWhiteSpace($payload)) { exit 0 }
# Background job workers inherit the dispatching agent's env, so the id would
# name an agent this session is not running in.
if ($env:CLAUDE_JOB_DIR) { exit 0 }
$endpoint = $env:${HOOK_ENV_ENDPOINT}
$agentId = $env:${HOOK_ENV_AGENT_ID}
$launchId = $env:${HOOK_ENV_LAUNCH_ID}
$taskId = $env:${HOOK_ENV_TASK_ID}
if ([string]::IsNullOrEmpty($endpoint)) { exit 0 }
if ([string]::IsNullOrEmpty($agentId)) { exit 0 }
if ([string]::IsNullOrEmpty($launchId)) { exit 0 }
if (-not (Test-Path -LiteralPath $endpoint -PathType Leaf)) { exit 0 }
$port = $null
$token = $null
foreach ($line in (Get-Content -LiteralPath $endpoint -ErrorAction SilentlyContinue)) {
  if ($line -match '^${HOOK_ENV_PORT}=(.+)$') { $port = $Matches[1].Trim() }
  elseif ($line -match '^${HOOK_ENV_TOKEN}=(.+)$') { $token = $Matches[1].Trim() }
}
if ([string]::IsNullOrEmpty($port)) { exit 0 }
if ([string]::IsNullOrEmpty($token)) { exit 0 }
try {
  Invoke-WebRequest -Uri "http://127.0.0.1:$port/hook/claude" -Method POST -Body ([string]$payload) \`
    -ContentType 'application/json' -TimeoutSec 2 -UseBasicParsing \`
    -Headers @{
      '${HOOK_TOKEN_HEADER}' = $token
      '${HOOK_AGENT_ID_HEADER}' = $agentId
      '${HOOK_LAUNCH_ID_HEADER}' = $launchId
      '${HOOK_TASK_ID_HEADER}' = $taskId
    } | Out-Null
} catch {
}
exit 0
`;
}
